### ISSUE TITLE
ConfigureALMDemo.bat doesn't set the time permanatly

### ISSUE THREAD

**Issue by rspaulino** [Microsoft/almvm#4]
I run ConfigureALMDemo.bat  as administrator and the time get set to 2013 but after a few minute the time switch back to today date.

**Comment by hsachinraj** [comment]
You need to disable the time synchronization option in Hyper-V.

Sachub

**Comment by rspaulino** [comment]
@hsachinraj I did and disconnect the VM from the internet and still happen.

**Comment by hsachinraj** [comment]
You need to disable the time synchronization so that the VM does not sync time with the host. You can do this by selecting the VM in Hyper-V manager, then 
1. Select Settings for the VM
2. Select Integration Services under the Management group
3. Uncheck "Time Synchronization"
4. Click Apply

This will stop the VM from syncing the time with the host continuously.
